export class Polity {
    /**
     * Key of this polity for dictionary lookups.
     * @type {string}
     */
    key;
    /**
     * Migrants that can be generated by this polity by their race.
     * @type { { [race: string]: number } }
     */
    migrants;
    /**
     * Technologies that this polity has access to.
     * @type { { [id: string]: boolean } }
     */
    technologies;

    constructor(key, migrants) {
        this.key = key;
        this.migrants = migrants;
        this.technologies = {};
    }
}

export const POLITIES = {};

POLITIES.crystalEmpire = new Polity(
        'crystalEmpire',
        {
            'earthPony': 1,
            'unicorn': 3,
        }
    );
POLITIES.deerConfederacy = new Polity(
        'deerConfederacy',
        {
            'deer': 4
        }
    );
POLITIES.dragonLands = new Polity(
        'dragonLands',
        {
            'dragon': 4
        }
    );
POLITIES.equestria = new Polity(
        'equestria',
        {
            'earthPony': 2,
            'pegasus': 1,
            'unicorn': 1,
        }
    );
POLITIES.farasi = new Polity(
        'farasi',
        {
            'zebra': 4
        }
    );
POLITIES.griffonstone = new Polity(
        'griffonstone',
        {
            'griffon': 4
        }
    );
POLITIES.qilinia = new Polity(
        'qilinia',
        {
            'kirin': 4
        }
    );
POLITIES.yakyakistan = new Polity(
        'yakyakistan',
        {
            'yak': 4
        }
    );
